<a href="https://colab.research.google.com/github/Mardavab/data_science_fundamentals/blob/main/chapter_04/numpy_challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Challenge

Create a NumPy ndarray object by using this list of numbers [7,8,4,5,1,2].


In [1]:
import numpy as np
arr = np.array([7,8,4,5,1,2])
print(arr)

[7 8 4 5 1 2]


Using slicing print the elements from index 3 to the end of the array.



In [2]:
print(arr[3:])

[5 1 2]


Using slicing print all the elements except the last one.



In [3]:
print(arr[0:-1])

[7 8 4 5 1]


Using slicing print the elements from index 1 to index 4 of the array.



In [4]:
print(arr[1:5])

[8 4 5 1]


Reshape the array into a 3 rows and 2 cols (3,2).



In [7]:
newarr = arr.reshape(3,2)
print(newarr)


[[7 8]
 [4 5]
 [1 2]]


Print all the array elements one by one (iterating).



In [8]:
for i in arr:
  print(i)

7
8
4
5
1
2


Create a new NumPy ndarray object by using this list of numbers [0,6,9].



In [10]:
newarr = np.array([0,6,9])
newarr

array([0, 6, 9])

Join the two arrays.



In [11]:
C_array = np.concatenate((arr, newarr))
C_array

array([7, 8, 4, 5, 1, 2, 0, 6, 9])




Using filtering print only the odd numbers of the joined array.



In [23]:
arr = np.array([7, 8, 4, 5, 1, 2, 0, 6, 9])
x = np.where(arr%2 == 1)
for i in x:
  print(arr[x])



[7 5 1 9]


Sort the joined array elements.



In [24]:
print(np.sort(arr))

[0 1 2 4 5 6 7 8 9]


Store in an array the names of the months.



In [ ]:
months = np.array(["enero", "febrero", "marzo", "abril", "junio", "julio", "agosto","septiembre", "octubre","noviembre","diciembre"])


Split the months array in 4 periods of 3 elements each one.



In [30]:
months = np.array(["enero", "febrero", "marzo", "abril", "junio", "julio", "agosto","septiembre", "octubre","noviembre","diciembre"])
newmonths = np.array_split(months, 4)
newmonths

[array(['enero', 'febrero', 'marzo'], dtype='<U10'),
 array(['abril', 'junio', 'julio'], dtype='<U10'),
 array(['agosto', 'septiembre', 'octubre'], dtype='<U10'),
 array(['noviembre', 'diciembre'], dtype='<U10')]

Create an array with genre information ['F','M','F','F','M','F'].



In [ ]:
genre = np.array(['F','M','F','F','M','F'])

Find the indexes where the value is F.



In [35]:
genre = np.array(['F','M','F','F','M','F'])
x = np.where(genre == 'F')
x

(array([0, 2, 3, 5]),)

Store in an array the age information [18,20,19,23,19,20].



In [ ]:
age = np.array([18,20,19,23,19,20])

Create a filter array with values < 20.



In [36]:
age = np.array([18,20,19,23,19,20])
filter_age = []

# go through each element in arr
for element in age:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element < 20:
    filter_age.append(True)
  else:
    filter_age.append(False)

newarr = age[filter_age]

print(filter_age)
print(newarr)

[True, False, True, False, True, False]
[18 19 19]


Change the 3 index element with a value of 22



In [37]:
age[3]=22
age

array([18, 20, 19, 22, 19, 20])

Print the 4 index element.

In [38]:
print(age[4])

19
